---
- name: Sécurisation et Mise à jour des VMs Ubuntu
  hosts: k3s_cluster
  become: true # Exécuter en root (sudo)
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les mises à jour de sécurité
      apt:
        upgrade: safe

    - name: Installer Unattended-Upgrades (Mises à jour automatiques)
      apt:
        name: unattended-upgrades
        state: present

    - name: Désactiver l'authentification par mot de passe SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Redémarrer SSH

  handlers:
    - name: Redémarrer SSH
      service:
        name: ssh
        state: restarted
